spring:
  datasource:
    url: jdbc:h2:file:./data/transactionDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /swagger-ui.html
